name: Build and deploy site
on:
push:
branches: [ main ]
workflow_dispatch: {}
schedule:
# GitHub Actions scheduled workflows support a minimum frequency of 5 minutes
- cron: '*/5 * * * *'


permissions:
contents: write


jobs:
build-and-deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Setup Python
uses: actions/setup-python@v4
with:
python-version: '3.11'


- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install -r requirements.txt


- name: Run scraper + generator
env:
GITHUB_REPOSITORY: ${{ github.repository }}
run: |
python scraper.py --out data.json
python generator.py --data data.json --out _site


- name: Deploy to GitHub Pages
uses: peaceiris/actions-gh-pages@v4
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
publish_dir: ./_site
